# Copyright (c) Ontic. (http://www.ontic.com.au). All rights reserved.
# See the COPYING file bundled with this package for license details.

---

- name: 'Exim | Configure system mail name.'
  become: yes
  template:
    src: 'mailname.j2'
    dest: '/etc/mailname'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'restart exim'
  when: 'exim_skip_mailname is undefined or exim_skip_mailname == False'

- name: 'Exim | Debian | Configure configuration variables.'
  become: yes
  lineinfile:
    dest: '{{ exim_conf_file }}'
    regexp: '^{{ item.option }}'
    line: '{{ item.option }}=''{{ item.value }}'''
    state: '{{ item.state | default(omit) }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'restart exim'
  with_items: '{{ exim_config }}'
  when: 'ansible_os_family == "Debian" and exim_config | default(None) != None'

- name: 'Exim | Debian | Configure remote password authentication.'
  become: yes
  template:
    src: 'passwd.client.j2'
    dest: '/etc/exim4/passwd.client'
    owner: 'root'
    group: 'root'
    mode: '0644'
  when: 'ansible_os_family == "Debian"'
